sx_mgmt_phy_module_info_get() SDK API --> sysfs
vadymhlushko-mlnx/sonic-buildimage pull request #24
Opened 2023-06-22 11:33 UTC by vadymhlushko-mlnx

#### Why I did it

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it

#### How to verify it

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ] 

#### Description for the changelog

#### Link to config_db schema for YANG module changes

#### A picture of a cute animal (not mandatory but encouraged)

2023-07-13 12:51 UTC, vadymhlushko-mlnx commented on platform/mellanox/mlnx-platform-api/sonic_platform/sfp.py
> +        sysfs_dir = "/sys/module/sx_netdev"
move to the beginning of the file

2023-07-13 12:51 UTC, vadymhlushko-mlnx commented on platform/mellanox/mlnx-platform-api/sonic_platform/sfp.py
> +        status_file = os.path.join(sysfs_dir, logical_ports[0], 'module', 'status')
consider to use constants as for `sysfs_dir`

2023-07-14 03:19 UTC, Junchao-Mellanox requested changes

2023-07-14 03:19 UTC, Junchao-Mellanox commented on platform/mellanox/mlnx-platform-api/sonic_platform/sfp.py
> +    platform_sfputil = sonic_platform_base.sonic_sfp.sfputilhelper.SfpUtilHelper()
Hi Vadym, we requested sdk to provide module based sysfs, we don't use logical port based sysfs here. If SDK did not provide it, please open a feature request for them.

2023-07-14 03:25 UTC, Junchao-Mellanox commented
Could you please add unit test for this change?

2023-07-18 09:55 UTC, vadymhlushko-mlnx commented
> Could you please add unit test for this change?

UT already implemented:
[test_sfp_get_error_status](https://github.com/sonic-net/sonic-buildimage/blob/bd413d20d2e264e2580e73867cd4cf3f097868b9/platform/mellanox/mlnx-platform-api/tests/test_sfp.py#L61)
[test_sfp_get_presence](https://github.com/sonic-net/sonic-buildimage/blob/bd413d20d2e264e2580e73867cd4cf3f097868b9/platform/mellanox/mlnx-platform-api/tests/test_sfp.py#L211)

2023-07-18 09:58 UTC, Junchao-Mellanox commented
> > Could you please add unit test for this change?
> 
> UT already implemented: [test_sfp_get_error_status](https://github.com/sonic-net/sonic-buildimage/blob/bd413d20d2e264e2580e73867cd4cf3f097868b9/platform/mellanox/mlnx-platform-api/tests/test_sfp.py#L61) [test_sfp_get_presence](https://github.com/sonic-net/sonic-buildimage/blob/bd413d20d2e264e2580e73867cd4cf3f097868b9/platform/mellanox/mlnx-platform-api/tests/test_sfp.py#L211)

Those two cases cannot test the new code you added/updated.

2023-07-20 01:38 UTC, Junchao-Mellanox approved these changes

2023-07-25 11:29 UTC, closed without merging